services:
    auth.provider.ojathelonius.oidc:
        class: ojathelonius\oidc\auth\provider\auth_oidc
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }
parameters:
    # Enable the usage of the super globals (_GET, _POST, _SERVER...)
    core.disable_super_globals: false
